# Generated by Django 4.1.1 on 2022-09-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statements", "0003_rule_bank"),
    ]

    operations = [
        migrations.AddField(
            model_name="line",
            name="balance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=9,
                null=True,
                verbose_name="solde",
            ),
        ),
    ]
